#!/usr/bin/env python3

"""
Pandoc filter to format citations and references according to ABNT style.
"""

from ABNTref import ABNTref

if __name__ == "__main__":
    abnt = ABNTref()
    abnt.Print()
